#' Function to grep search labels in tree and plot all connected components
#' 
#' @param graph (required) input graph of trait ontology generated by, e.g., read_ontology() or stemsearch()
#' @param pattern text to search for (regular expression)
#' @param plot whether to plot (logical)
#' @param mode whether to search for all edges to current node ("in") or away from ("out")
#' @param ... additional arguments passed to the `plot.igraph` function
#' 
#' @export
#' 
searchtree <- function(graph, pattern, plot=TRUE, mode="out", ...) {
	id <- grep(pattern, V(graph)$name)
	subcomps <- lapply(id, subcomponent, graph=graph, mode=mode)
	id <- unique(unlist(subcomps))
	newgraph <- simplify(induced_subgraph(graph, id))
	if (plot) {
		plot(newgraph, ...)
	}
	invisible(newgraph)
}
